export interface EmojiItem {
    char: string;
    name: string;
    keywords: string[];
}

export const EMOJI_LIST: EmojiItem[] = [
    // 🏋️ สุขภาพ ออกกำลังกาย กีฬา (25 ไอคอน)
    { char: '🧘', name: 'สมาธิ', keywords: ['meditate', 'meditation', 'yoga', 'สมาธิ', 'โยคะ', 'ผ่อนคลาย'] },
    { char: '🏃', name: 'วิ่ง', keywords: ['run', 'running', 'jogging', 'วิ่ง', 'ออกกำลังกาย'] },
    { char: '🚶', name: 'เดิน', keywords: ['walk', 'walking', 'เดิน', 'ก้าว'] },
    { char: '🚴', name: 'ปั่นจักรยาน', keywords: ['bike', 'cycling', 'จักรยาน', 'ปั่น'] },
    { char: '🏋️', name: 'ยกเวท / ฟิตเนส', keywords: ['gym', 'workout', 'weights', 'ฟิตเนส', 'เวท', 'ยกน้ำหนัก'] },
    { char: '🏊', name: 'ว่ายน้ำ', keywords: ['swim', 'swimming', 'ว่ายน้ำ'] },
    { char: '⚽', name: 'ฟุตบอล', keywords: ['football', 'soccer', 'บอล', 'ฟุตบอล'] },
    { char: '🏀', name: 'บาสเกตบอล', keywords: ['basketball', 'บาส'] },
    { char: '🏸', name: 'แบดมินตัน', keywords: ['badminton', 'แบด'] },
    { char: '🥊', name: 'ชกมวย', keywords: ['boxing', 'มวย', 'ชกมวย'] },
    { char: '🎾', name: 'เทนนิส', keywords: ['tennis', 'เทนนิส'] },
    { char: '🏐', name: 'วอลเลย์บอล', keywords: ['volleyball', 'วอลเลย์'] },
    { char: '⛳', name: 'กอล์ฟ', keywords: ['golf', 'กอล์ฟ'] },
    { char: '🎳', name: 'โบว์ลิ่ง', keywords: ['bowling', 'โบว์ลิ่ง'] },
    { char: '🛹', name: 'สเก็ตบอร์ด', keywords: ['skateboard', 'สเก็ต'] },
    { char: '🏄', name: 'โต้คลื่น', keywords: ['surf', 'surfing', 'เซิร์ฟ'] },
    { char: '🧗', name: 'ปีนเขา', keywords: ['climb', 'climbing', 'ปีนเขา'] },
    { char: '🤸', name: 'ยืดเหยียด / ยิมนาสติก', keywords: ['stretch', 'gymnastics', 'ยืดตัว', 'ยิมนาสติก'] },
    { char: '😴', name: 'นอนหลับ', keywords: ['sleep', 'sleeping', 'rest', 'นอน', 'หลับ', 'พักผ่อน'] },
    { char: '💧', name: 'ดื่มน้ำ', keywords: ['water', 'drink', 'น้ำ', 'ดื่มน้ำ', 'สุขภาพ'] },
    { char: '💊', name: 'ทานยา', keywords: ['medicine', 'pill', 'ยา', 'วิตามิน', 'ทานยา'] },
    { char: '🩺', name: 'ตรวจสุขภาพ', keywords: ['health', 'doctor', 'checkup', 'หมอ', 'สุขภาพ'] },
    { char: '🩸', name: 'บริจาคเลือด', keywords: ['blood', 'donate', 'บริจาค', 'เลือด'] },
    { char: '🧖', name: 'สปา / ซาวน่า', keywords: ['spa', 'sauna', 'สปา', 'ซาวน่า'] },

    // ☕ อาหาร เครื่องดื่ม สุขภาพ (25 ไอคอน)
    { char: '☕', name: 'กาแฟ', keywords: ['coffee', 'cafe', 'กาแฟ', 'คาเฟ่'] },
    { char: '🍵', name: 'ชา / ชาเขียว', keywords: ['tea', 'matcha', 'ชา', 'ชาเขียว'] },
    { char: '🧋', name: 'ชาไข่มุก', keywords: ['boba', 'bubble tea', 'ชาไข่มุก'] },
    { char: '🥛', name: 'นม', keywords: ['milk', 'นม'] },
    { char: '🥤', name: 'น้ำหวาน / น้ำอัดลม', keywords: ['soda', 'drink', 'น้ำอัดลม', 'น้ำหวาน'] },
    { char: '🍺', name: 'เบียร์', keywords: ['beer', 'เบียร์', 'สังสรรค์'] },
    { char: '🍷', name: 'ไวน์', keywords: ['wine', 'ไวน์'] },
    { char: '🥗', name: 'สลัด / อาหารคลีน', keywords: ['salad', 'clean', 'อาหารคลีน', 'สลัด'] },
    { char: '🍳', name: 'อาหารเช้า', keywords: ['breakfast', 'egg', 'อาหารเช้า', 'ไข่ดาว'] },
    { char: '🍱', name: 'ข้าวกล่อง / ข้าวเย็น', keywords: ['lunch', 'bento', 'ข้าวกล่อง', 'มื้อเที่ยง'] },
    { char: '🍜', name: 'ก๋วยเตี๋ยว / ราเมง', keywords: ['noodle', 'ramen', 'ก๋วยเตี๋ยว', 'ราเมง'] },
    { char: '🍕', name: 'พิซซ่า', keywords: ['pizza', 'พิซซ่า'] },
    { char: '🍔', name: 'เบอร์เกอร์', keywords: ['burger', 'fastfood', 'เบอร์เกอร์'] },
    { char: '🍣', name: 'ซูชิ', keywords: ['sushi', 'ซูชิ', 'อาหารญี่ปุ่น'] },
    { char: '🍞', name: 'ขนมปัง', keywords: ['bread', 'toast', 'ขนมปัง'] },
    { char: '🍎', name: 'ผลไม้ / แอปเปิ้ล', keywords: ['apple', 'fruit', 'ผลไม้', 'แอปเปิ้ล'] },
    { char: '🍌', name: 'กล้วย', keywords: ['banana', 'กล้วย'] },
    { char: '🥦', name: 'ผัก', keywords: ['vegetable', 'broccoli', 'ผัก'] },
    { char: '🥑', name: 'อะโวคาโด', keywords: ['avocado', 'อะโวคาโด'] },
    { char: '🥩', name: 'สเต๊ก / เนื้อสัตว์', keywords: ['meat', 'steak', 'สเต๊ก', 'เนื้อ'] },
    { char: '🥞', name: 'แพนเค้ก', keywords: ['pancake', 'แพนเค้ก'] },
    { char: '🍰', name: 'เค้ก / ของหวาน', keywords: ['cake', 'dessert', 'เค้ก', 'ขนม'] },
    { char: '🍦', name: 'ไอศกรีม', keywords: ['icecream', 'ไอติม', 'ไอศกรีม'] },
    { char: '🍿', name: 'ป๊อปคอร์น', keywords: ['popcorn', 'ป๊อปคอร์น'] },
    { char: '🍫', name: 'ช็อกโกแลต', keywords: ['chocolate', 'ช็อกโกแลต'] },

    // 💼 งาน การเรียน พัฒนาตนเอง (25 ไอคอน)
    { char: '📚', name: 'อ่านหนังสือ', keywords: ['read', 'reading', 'book', 'หนังสือ', 'อ่านหนังสือ'] },
    { char: '💼', name: 'ทำงาน', keywords: ['work', 'job', 'office', 'งาน', 'ทำงาน'] },
    { char: '💻', name: 'เขียนโค้ด / โน้ตบุ๊ก', keywords: ['code', 'coding', 'laptop', 'computer', 'โค้ด', 'คอม'] },
    { char: '🖥️', name: 'คอมพิวเตอร์ตั้งโต๊ะ', keywords: ['pc', 'desktop', 'คอมพิวเตอร์'] },
    { char: '📱', name: 'มือถือ / เล่นสมาร์ทโฟน', keywords: ['phone', 'mobile', 'มือถือ', 'สมาร์ทโฟน'] },
    { char: '✍️', name: 'เขียนไดอารี่ / บันทึก', keywords: ['write', 'writing', 'journal', 'เขียน', 'จด'] },
    { char: '🎓', name: 'เรียน / สอบ', keywords: ['study', 'learn', 'exam', 'เรียน', 'ติว', 'สอบ'] },
    { char: '🗣️', name: 'ฝึกภาษา', keywords: ['language', 'english', 'speak', 'ภาษา', 'พูด'] },
    { char: '💡', name: 'คิดไอเดีย', keywords: ['idea', 'think', 'brainstorm', 'ไอเดีย'] },
    { char: '📈', name: 'การเงิน / กราฟ', keywords: ['finance', 'chart', 'stock', 'หุ้น', 'การเงิน'] },
    { char: '📊', name: 'วิเคราะห์ข้อมูล', keywords: ['analytics', 'data', 'วิเคราะห์', 'รายงาน'] },
    { char: '📝', name: 'ทำแบบฝึกหัด / โน้ต', keywords: ['note', 'task', 'การบ้าน', 'โน้ต'] },
    { char: '📁', name: 'จัดระเบียบไฟล์', keywords: ['folder', 'file', 'เอกสาร', 'ไฟล์'] },
    { char: '📅', name: 'วางแผนตารางเวลา', keywords: ['calendar', 'schedule', 'ปฏิทิน', 'ตารางงาน'] },
    { char: '✉️', name: 'ตอบอีเมล', keywords: ['email', 'mail', 'อีเมล', 'จดหมาย'] },
    { char: '🔍', name: 'ค้นคว้าวิจัย', keywords: ['search', 'research', 'ค้นหา', 'วิจัย'] },
    { char: '🔬', name: 'ทดลอง / วิทยาศาสตร์', keywords: ['science', 'lab', 'ทดลอง', 'วิทยาศาสตร์'] },
    { char: '📐', name: 'คำนวณ / ออกแบบ', keywords: ['math', 'design', 'คำนวณ', 'คณิต'] },
    { char: '🎨', name: 'วาดรูป / ศิลปะ', keywords: ['art', 'draw', 'paint', 'วาดรูป', 'ศิลปะ'] },
    { char: '🎭', name: 'การแสดง / ซ้อมละคร', keywords: ['drama', 'act', 'การแสดง'] },
    { char: '🎙️', name: 'จัดพอดแคสต์ / อัดเสียง', keywords: ['podcast', 'record', 'อัดเสียง', 'พอดแคสต์'] },
    { char: '📢', name: 'การตลาด / ประชาสัมพันธ์', keywords: ['marketing', 'promote', 'การตลาด'] },
    { char: '🤝', name: 'ประชุม / เจรจา', keywords: ['meeting', 'deal', 'ประชุม', 'คุยงาน'] },

    // 🏠 งานบ้าน กิจวัตรประจำวัน (25 ไอคอน)
    { char: '🧹', name: 'ทำความสะอาด', keywords: ['clean', 'sweep', 'กวาด', 'ถู', 'ทำความสะอาด'] },
    { char: '🧺', name: 'ซักผ้า / ตากผ้า', keywords: ['laundry', 'wash', 'ซักผ้า', 'ตากผ้า'] },
    { char: '🍽️', name: 'ล้างจาน', keywords: ['dishes', 'wash', 'ล้างจาน'] },
    { char: '🍳', name: 'ทำอาหารในครัว', keywords: ['cook', 'kitchen', 'ทำครัว', 'เข้าครัว'] },
    { char: '🚗', name: 'ขับรถ', keywords: ['drive', 'car', 'ขับรถ'] },
    { char: '🚌', name: 'นั่งรถเมล์ / รถสาธารณะ', keywords: ['bus', 'commute', 'รถเมล์', 'เดินทาง'] },
    { char: '🚲', name: 'ขี่จักรยานเดินทาง', keywords: ['bicycle', 'จักรยาน'] },
    { char: '🛒', name: 'จ่ายตลาด / ซื้อของ', keywords: ['shopping', 'market', 'จ่ายตลาด', 'ซื้อของ'] },
    { char: '🛍️', name: 'ช้อปปิ้ง', keywords: ['shopping', 'mall', 'ช้อปปิ้ง', 'ซื้อเสื้อผ้า'] },
    { char: '🪴', name: 'รดน้ำต้นไม้ / ทำสวน', keywords: ['plant', 'garden', 'ต้นไม้', 'ทำสวน'] },
    { char: '🐶', name: 'เลี้ยงสุนัข', keywords: ['dog', 'pet', 'หมา', 'สุนัข'] },
    { char: '🐱', name: 'เลี้ยงแมว', keywords: ['cat', 'pet', 'แมว'] },
    { char: '🛁', name: 'อาบน้ำ', keywords: ['bath', 'shower', 'อาบน้ำ'] },
    { char: '🛋️', name: 'พักผ่อนบนโซฟา', keywords: ['sofa', 'relax', 'โซฟา', 'นั่งเล่น'] },
    { char: '🛏️', name: 'จัดเตียงนอน', keywords: ['bed', 'makebed', 'จัดเตียง'] },
    { char: '🔑', name: 'ไขกุญแจ / ล็อกบ้าน', keywords: ['key', 'lock', 'กุญแจ', 'บ้าน'] },
    { char: '🧽', name: 'เช็ดทำความสะอาด', keywords: ['sponge', 'wipe', 'เช็ด'] },
    { char: '🧼', name: 'ล้างมือ', keywords: ['soap', 'wash', 'สบู่', 'ล้างมือ'] },
    { char: '⛽', name: 'เติมน้ำมัน', keywords: ['gas', 'fuel', 'เติมน้ำมัน', 'ปั๊ม'] },
    { char: '💳', name: 'ชำระบิล / บัตร', keywords: ['bill', 'pay', 'card', 'จ่ายบิล', 'บัตรเครดิต'] },
    { char: '📦', name: 'แกะพัสดุ / ส่งของ', keywords: ['parcel', 'box', 'พัสดุ', 'ส่งของ'] },
    { char: '🗑️', name: 'ทิ้งขยะ', keywords: ['trash', 'garbage', 'ขยะ', 'ทิ้งขยะ'] },
    { char: '🛠️', name: 'ซ่อมแซมบ้าน', keywords: ['fix', 'repair', 'tools', 'ซ่อม', 'เครื่องมือ'] },

    // 🎮 พักผ่อน ความบันเทิง (20 ไอคอน)
    { char: '🎮', name: 'เล่นเกม', keywords: ['game', 'gaming', 'play', 'เกม', 'เล่นเกม'] },
    { char: '🎸', name: 'เล่นกีตาร์', keywords: ['guitar', 'music', 'กีตาร์'] },
    { char: '🎹', name: 'เล่นเปียโน / คีย์บอร์ด', keywords: ['piano', 'music', 'เปียโน'] },
    { char: '🎬', name: 'ดูหนัง / ซีรีส์', keywords: ['movie', 'netflix', 'หนัง', 'ซีรีส์'] },
    { char: '🎧', name: 'ฟังเพลง', keywords: ['listen', 'music', 'songs', 'ฟังเพลง'] },
    { char: '📺', name: 'ดูทีวี', keywords: ['tv', 'television', 'ทีวี'] },
    { char: '📷', name: 'ถ่ายรูป / ตากล้อง', keywords: ['photo', 'camera', 'ถ่ายรูป', 'กล้อง'] },
    { char: '🎲', name: 'เล่นบอร์ดเกม', keywords: ['boardgame', 'dice', 'บอร์ดเกม'] },
    { char: '🎯', name: 'ปาลูกดอก / เป้าหมาย', keywords: ['darts', 'target', 'เป้าหมาย'] },
    { char: '♟️', name: 'เล่นหมากรุก', keywords: ['chess', 'หมากรุก'] },
    { char: '🍿', name: 'ดูภาพยนตร์โรง', keywords: ['cinema', 'popcorn', 'โรงหนัง'] },
    { char: '⛺', name: 'แค้มปิ้ง / กางเต็นท์', keywords: ['camp', 'camping', 'เต็นท์', 'แค้มปิ้ง'] },
    { char: '✈️', name: 'ท่องเที่ยว / ขึ้นเครื่อง', keywords: ['travel', 'flight', 'เที่ยว', 'เครื่องบิน'] },
    { char: '🏖️', name: 'เที่ยวทะเล', keywords: ['beach', 'sea', 'ทะเล', 'ชายหาด'] },
    { char: '🗺️', name: 'วางแผนเที่ยว', keywords: ['map', 'trip', 'แผนที่', 'เที่ยว'] },
    { char: '🎪', name: 'เที่ยวงานเทศกาล', keywords: ['event', 'festival', 'งานวัด', 'เทศกาล'] },

    // 🙏 ทำบุญ จิตใจ จิตอาสา อื่นๆ (15 ไอคอน)
    { char: '🙏', name: 'ไหว้พระ / สวดมนต์', keywords: ['pray', 'buddha', 'สวดมนต์', 'ไหว้พระ', 'พระ'] },
    { char: '🪙', name: 'หยอดกระปุก / ทำบุญ', keywords: ['save', 'money', 'piggy', 'ออมเงิน', 'หยอดกระปุก', 'ทำบุญ'] },
    { char: '❤️', name: 'จิตอาสา / ทำความดี', keywords: ['heart', 'good', 'help', 'ทำดี', 'จิตอาสา', 'บริจาค'] },
    { char: '🕊️', name: 'ปล่อยนก / ทำบุญสัตว์', keywords: ['bird', 'peace', 'ปล่อยนก', 'ทำบุญ'] },
    { char: '🕯️', name: 'จุดเทียน / เวียนเทียน', keywords: ['candle', 'light', 'เทียน', 'เวียนเทียน'] },
    { char: '☀️', name: 'รับแดดเช้า / ตื่นเช้า', keywords: ['sun', 'morning', 'ตื่นเช้า', 'แดด'] },
    { char: '🌙', name: 'ไหว้พระก่อนนอน', keywords: ['moon', 'night', 'กลางคืน', 'ก่อนนอน'] },
    { char: '⭐', name: 'เป้าหมายดาว', keywords: ['star', 'goal', 'ดาว', 'เป้าหมาย'] },
    { char: '🍀', name: 'ความโชคดี / พลังบวก', keywords: ['clover', 'luck', 'โชคดี', 'พลังบวก'] },
    { char: '🎁', name: 'ให้ของขวัญ', keywords: ['gift', 'present', 'ของขวัญ'] },
    { char: '💎', name: 'เป้าหมายอันมีค่า', keywords: ['gem', 'diamond', 'เพชร', 'สำคัญ'] },
    { char: '📌', name: 'หมุดทั่วไป', keywords: ['pin', 'general', 'หมุด', 'ทั่วไป'] }
];
